class RomaniaLocations {
  static const List<String> countries = ['Romania'];

  static const List<String> counties = [
    'Alba',
    'Arad',
    'Argeș',
    'Bacău',
    'Bihor',
    'Bistrița-Năsăud',
    'Botoșani',
    'Brașov',
    'Brăila',
    'București',
    'Buzău',
    'Caraș-Severin',
    'Călărași',
    'Cluj',
    'Constanța',
    'Covasna',
    'Dâmbovița',
    'Dolj',
    'Galați',
    'Giurgiu',
    'Gorj',
    'Harghita',
    'Hunedoara',
    'Ialomița',
    'Iași',
    'Ilfov',
    'Maramureș',
    'Mehedinți',
    'Mureș',
    'Neamț',
    'Olt',
    'Prahova',
    'Satu Mare',
    'Sălaj',
    'Sibiu',
    'Suceava',
    'Teleorman',
    'Timiș',
    'Tulcea',
    'Vaslui',
    'Vâlcea',
    'Vrancea',
  ];

  static const Map<String, List<String>> localitiesByCounty = {
    'Alba': ['Alba Iulia', 'Aiud', 'Blaj', 'Câmpeni', 'Sebeș'],
    'Arad': ['Arad', 'Ineu', 'Lipova', 'Pecica', 'Nădlac'],
    'Argeș': ['Pitești', 'Câmpulung', 'Curtea de Argeș', 'Mioveni', 'Topoloveni'],
    'Bacău': ['Bacău', 'Onești', 'Moinești', 'Comănești', 'Buhuși'],
    'Bihor': ['Oradea', 'Salonta', 'Marghita', 'Beiuș', 'Aleșd'],
    'Bistrița-Năsăud': ['Bistrița', 'Năsăud', 'Beclean', 'Sângeorz-Băi'],
    'Botoșani': ['Botoșani', 'Dorohoi', 'Darabani', 'Săveni', 'Flămânzi'],
    'Brașov': ['Brașov', 'Făgăraș', 'Săcele', 'Codlea', 'Râșnov'],
    'Brăila': ['Brăila', 'Ianca', 'Făurei', 'Însurăței'],
    'București': ['Sector 1', 'Sector 2', 'Sector 3', 'Sector 4', 'Sector 5', 'Sector 6'],
    'Buzău': ['Buzău', 'Râmnicu Sărat', 'Nehoiu', 'Pogoanele'],
    'Caraș-Severin': ['Reșița', 'Caransebeș', 'Oravița', 'Moldova Nouă'],
    'Călărași': ['Călărași', 'Oltenița', 'Lehliu-Gară', 'Budești'],
    'Cluj': ['Cluj-Napoca', 'Turda', 'Dej', 'Câmpia Turzii', 'Gherla'],
    'Constanța': ['Constanța', 'Mangalia', 'Medgidia', 'Năvodari', 'Cernavodă'],
    'Covasna': ['Sfântu Gheorghe', 'Târgu Secuiesc', 'Covasna', 'Baraolt'],
    'Dâmbovița': ['Târgoviște', 'Moreni', 'Pucioasa', 'Găești'],
    'Dolj': ['Craiova', 'Băilești', 'Calafat', 'Filiași'],
    'Galați': ['Galați', 'Tecuci', 'Târgu Bujor', 'Berești'],
    'Giurgiu': ['Giurgiu', 'Bolintin-Vale', 'Mihăilești'],
    'Gorj': ['Târgu Jiu', 'Motru', 'Rovinari', 'Târgu Cărbunești'],
    'Harghita': ['Miercurea Ciuc', 'Odorheiu Secuiesc', 'Gheorgheni', 'Toplița'],
    'Hunedoara': ['Deva', 'Hunedoara', 'Petroșani', 'Lupeni', 'Orăștie'],
    'Ialomița': ['Slobozia', 'Fetești', 'Urziceni', 'Țăndărei'],
    'Iași': ['Iași', 'Pașcani', 'Hârlău', 'Târgu Frumos'],
    'Ilfov': ['Buftea', 'Voluntari', 'Otopeni', 'Popești-Leordeni', 'Pantelimon'],
    'Maramureș': ['Baia Mare', 'Sighetu Marmației', 'Borșa', 'Vișeu de Sus'],
    'Mehedinți': ['Drobeta-Turnu Severin', 'Orșova', 'Strehaia', 'Vânju Mare'],
    'Mureș': ['Târgu Mureș', 'Sighișoara', 'Reghin', 'Târnăveni'],
    'Neamț': ['Piatra Neamț', 'Roman', 'Târgu Neamț', 'Bicaz'],
    'Olt': ['Slatina', 'Caracal', 'Balș', 'Corabia'],
    'Prahova': ['Ploiești', 'Câmpina', 'Sinaia', 'Băicoi', 'Mizil'],
    'Satu Mare': ['Satu Mare', 'Carei', 'Negrești-Oaș', 'Tășnad'],
    'Sălaj': ['Zalău', 'Șimleu Silvaniei', 'Jibou', 'Cehu Silvaniei'],
    'Sibiu': ['Sibiu', 'Mediaș', 'Cisnădie', 'Agnita'],
    'Suceava': ['Suceava', 'Fălticeni', 'Rădăuți', 'Câmpulung Moldovenesc', 'Vatra Dornei'],
    'Teleorman': ['Alexandria', 'Roșiorii de Vede', 'Turnu Măgurele', 'Zimnicea'],
    'Timiș': ['Timișoara', 'Lugoj', 'Sânnicolau Mare', 'Jimbolia'],
    'Tulcea': ['Tulcea', 'Măcin', 'Babadag', 'Isaccea'],
    'Vaslui': ['Vaslui', 'Bârlad', 'Huși', 'Negrești'],
    'Vâlcea': ['Râmnicu Vâlcea', 'Drăgășani', 'Băbeni', 'Horezu'],
    'Vrancea': ['Focșani', 'Adjud', 'Mărășești', 'Odobești'],
  };

  static List<String> localitiesForCounty(String? county) {
    if (county == null) return const [];
    return localitiesByCounty[county] ?? const [];
  }
}
