Map<String, Map<String, String>> texts = {
  "RO": {
    "login": "Conectare",
    "register": "Înregistrare",
    "email": "E-mail",
    "title": "Titlu",
    "description": "Descriere",
    "password": "Parolă",
    "confirm": "Confirmare Parola",
    "remember": "Ține minte credențialele",
    "forgot": "Mi-am uitat parola",
    "user": "Utilizator",
    "company": "Companie",
    "companyName": "Nume companie",
    "first": "Prenume",
    "last": "Nume",
    "passMismatch": "Parolele nu coincid!",
    "lower": "Cel puțin o literă mică",
    "upper": "Cel puțin o literă mare",
    "number": "Cel puțin o cifră",
    "special": "Cel puțin un caracter special",
    "emailInfo":
        "Vă rugăm să introduceți o adresă de e-mail validă pentru a vă putea trimite credențialele de conectare.",
    "send": "Trimite",
    "appName": "CareerSuitUp",
    "leftHeadingLogin": "Intră în cockpitul carierei tale",
    "leftHeadingRegister": "Construiește-ți identitatea profesională de mâine",
    "leftSubtitle":
        "Recrutare inteligentă, orientată pe competențe și rezultate reale",
    "leftDescriptionLogin":
        "Activează profilul tău, urmărește oportunități relevante și conectează-te rapid cu angajatori verificați.",
    "leftDescriptionRegister":
        "Creează-ți contul și pornește într-un ecosistem în care candidații și companiile colaborează transparent, în timp real.",
    "leftSignalRealtime": "Recomandări în timp real",
    "leftSignalTrust": "Profiluri verificate",
    "leftSignalPrecision": "Matching precis competențe-job",
    "gdprTitle": "Politica de Confidențialitate și Prelucrarea Datelor",
    "gdprDescription":
        "Prin continuarea înregistrării, confirmi că ți-ai citit și înțeles politica de confidențialitate și consimți prelucrarea datelor personale în conformitate cu GDPR.",
    "gdprLink": "Citește política de confidențialitate completă",
    "gdprLinkPlaceholder": "Deschiderea documentului oficial GDPR...",
    "gdprConsent":
        "Sunt de acord cu prelucrarea datelor mele personale conform GDPR",
    "cancel": "Anulare",
    "save": "Salvează",
    "confirmAction": "Confirmă",
    "accept": "Accept",
    "back": "Înapoi",
    "next": "Continuă",
    "country": "Țara",
    "userLocationSection": "Date de localizare",
    "hrFirstName": "Prenumele reprezentantului HR",
    "hrLastName": "Numele reprezentantului HR",
    "hrEmail": "Email-ul reprezentantului HR",
    "hrContactSection": "Date de contact pentru persoana HR",
    "userProfileSection": "Completare profil candidat",
    "phone": "Telefon",
    "county": "Județ",
    "city": "Localitate",
    "professionalTitle": "Titlu profesional",
    "profileSummary": "Descriere profil",
    "socialLinks": "Link-uri principale",
    "experienceSection": "Experiență",
    "skillsSection": "Competențe",
    "educationSection": "Educație",
    "projectsSection": "Proiecte",
    "activityFeed": "Flux activitate",
    "activityPostLabel": "Postare",
    "activityEmptyState": "Nu există postări încă.",
    "postPlaceholder": "Ce ai vrea să împărtășești?",
    "postAction": "Publică",
    "editPost": "Editează postarea",
    "deletePost": "Șterge postarea",
    "addEmoji": "Adaugă emoji",
    "addSticker": "Adaugă sticker",
    "addAttachment": "Adaugă atașament",
    "pickEmoji": "Alege un emoji",
    "pickSticker": "Alege un sticker",
    "activityComments": "Comentarii",
    "activityCommentPlaceholder": "Scrie un comentariu...",
    "commentAction": "Comentează",
    "activityPostOwnerOnly":
        "Doar deținătorul acestui profil poate publica postări aici. Tu poți comenta la postările existente.",
    "emojiCategorySmileys": "Zâmbete",
    "emojiCategoryWork": "Muncă",
    "emojiCategoryCelebrate": "Sărbătoare",
    "emojiCategoryPeople": "Persoane",
    "stickerCategoryBusiness": "Business",
    "stickerCategoryMotivation": "Motivație",
    "stickerCategoryReactions": "Reacții",
    "stickerCategoryStatus": "Status",
    "clear": "Șterge",
    "present": "Prezent",
    "professionalStatus": "Status profesional",
    "professionalStatusOpenToWork": "Open to Work",
    "professionalStatusHired": "Hired",
    "professionalStatusNotAvailable": "Indisponibil",
    "yearsExperience": "Ani de experiență",
    "experienceMaxThreeHint": "Poți adăuga maximum 5 experiențe profesionale.",
    "experienceEmptyState": "Nu ai adăugat experiențe profesionale încă.",
    "experienceItemLabel": "Experiență",
    "experienceShortDescription": "Scurtă descriere",
    "startMonth": "Luna început",
    "startYear": "An început",
    "endMonth": "Luna final",
    "endYear": "An final",
    "invalidEndDate": "Data de final trebuie să fie după data de început",
    "experienceCurrentRole": "Lucrez aici în prezent",
    "addExperienceItem": "Adaugă experiență",
    "educationMaxThreeHint": "Poți adăuga maximum 5 studii.",
    "educationEmptyState": "Nu ai adăugat studii încă.",
    "educationItemLabel": "Educație",
    "universityName": "Universitate",
    "educationCurrentRole": "Studiez aici în prezent",
    "addEducationItem": "Adaugă educație",
    "projectsMaxHint": "Poți adăuga maximum 10 proiecte.",
    "projectsEmptyState": "Nu ai adăugat proiecte încă.",
    "projectItemLabel": "Proiect",
    "projectTitleLabel": "Titlu proiect",
    "projectDescriptionLabel": "Descriere proiect",
    "projectGithubLabel": "Link GitHub (opțional)",
    "projectCurrentLabel": "Proiect în desfășurare",
    "addProjectItem": "Adaugă proiect",
    "educationLevel": "Forma de învățământ",
    "educationFormLabel": "Forma de învățământ",
    "educationInstitutionLabel": "Unitate de învățământ",
    "lastEducationInstitution": "Ultima unitate de învățământ absolvită",
    "specialization": "Specializare",
    "gender": "Gen",
    "genderMale": "Masculin",
    "genderFemale": "Feminin",
    "birthDate": "Data nașterii",
    "pickBirthDate": "Alege data nașterii",
    "accountCreatedDate": "Data creării contului",
    "accountCreatedTime": "Ora creării contului",
    "cvAttachmentSection": "Atașament CV",
    "uploadCv": "Încarcă CV (PDF/DOC/DOCX)",
    "cvAttachmentSelected": "Fișier selectat",
    "cvAttachmentMissing": "Atașament CV obligatoriu",
    "selectedValueMissing": "Valoarea selectată nu există în listă",
    "completeAllFields": "Completează toate câmpurile obligatorii",
    "loginEmailNotFound":
        "Nu există încă un cont creat pentru adresa de e-mail specificată.",
    "loginWrongPassword":
        "Parola introdusă nu este corectă. Vă rugăm reîncercați logarea.",
    "loginRetryIn": "Poți încerca din nou în",
    "loginGenericError": "A apărut o eroare la autentificare.",
    "loginTwoFactorRequired":
        "Introdu codul din aplicația de autentificare pentru a continua.",
    "loginTwoFactorInvalid":
        "Codul de autentificare cu doi factori nu este valid.",
    "loginTwoFactorDialogTitle": "Cod de autentificare 2FA",
    "loginTwoFactorDialogDescription":
        "Introdu codul din Google Authenticator.",
    "registerSuccessTitle": "Cont creat cu succes",
    "registerSuccessMessage": "Contul a fost creat cu succes.",
    "registerEmailAlreadyExists":
        "Exista deja un cont asociat acestei adrese de e-mail.",
    "ok": "OK",
    "profile": "Profil",
    "home": "Home",
    "achievements": "Realizări",
    "settings": "Setări",
    "accountDetails": "Date cont",
    "locationDetails": "Date de localizare",
    "profileDetails": "Profil",
    "attachments": "Atașamente",
    "companyDetails": "Date companie",
    "hrDetails": "Contact HR",
    "saveChanges": "Salvează",
    "saveAll": "Salvează tot",
    "previewProfile": "Previzualizare draft profil",
    "settingsDraftPending":
        "Ai modificări nesalvate. Poți previzualiza profilul înainte de salvare.",
    "settingsDraftSynced": "Nu există modificări nesalvate.",
    "profilePreviewDraftTitle": "Previzualizare profil (draft)",
    "profilePreviewDraftDescription":
        "Acesta este modul în care profilul public va arăta după salvarea modificărilor.",
    "profilePreviewNoPublicFields":
        "Nu există câmpuri publice vizibile pe baza setărilor curente.",
    "settingsSubcategoryVisibilityHint":
        "Deschide subcategoria și setează lock/unlock pentru câmpurile afișate pe profil.",
    "visibility": "Vizibilitate",
    "public": "Public",
    "private": "Privat",
    "cvAvailable": "CV disponibil",
    "cvNotAvailable": "CV lipsă",
    "profilePhoto": "Poză de profil",
    "uploadProfilePhoto": "Încarcă poză de profil",
    "photoSet": "Setată",
    "photoMissing": "Lipsă",
    "message": "Mesaj",
    "messages": "Mesaje",
    "notifications": "Notificări",
    "downloadCvAction": "Download CV",
    "searchCandidatesJobs": "Caută candidați, job-uri...",
    "searchInProfiles": "Search text în Profiles",
    "searchInJobs": "Search text în Jobs",
    "searchInActivities": "Search text în Activities",
    "searchAction": "Caută",
    "closeSearch": "Închide căutarea",
    "searchSelfBadge": "Eu",
    "searchNoResults": "Nu am găsit profiluri pentru acest text.",
    "searchFiltersLabel": "Filtre căutare:",
    "searchFilterAll": "Toate câmpurile",
    "searchFilterName": "Nume și prenume",
    "searchFilterEmail": "Email",
    "searchFilterJobTitle": "Titlu profesie",
    "homeTileActivities": "Activități",
    "homeTileActivitiesSubtitle": "Explorează comunitatea",
    "homeTileJobs": "Job-uri",
    "homeTileJobsSubtitle": "Descoperă oportunități noi",
    "homeCommunityTitle": "Noutăți din comunitate",
    "homeCommunityPost1": "Entuziasmat să încep noul job! #NewBeginnings",
    "homeCommunityPost2": "Angajăm! Căutăm un specialist Marketing.",
    "homeCommunityPost3":
        "Noapte excelentă la networking! Am cunoscut oameni super.",
    "homeActivitiesPlaceholder": "Pagina Activități este în pregătire.",
    "homeJobsPlaceholder": "Pagina Job-uri este în pregătire.",
    "activitiesTitle": "Activități",
    "addActivity": "Adaugă activitate",
    "asPayer": "Ca plătitor",
    "asProvider": "Ca prestator",
    "postedActivities": "Activitățile postate",
    "upcomingEvents": "Evenimente viitoare",
    "allActivities": "Activități",
    "recurringActivities": "Activități recurente",
    "oneTimeActivities": "Activități unice",
    "sortPostedDesc": "Postare ↓",
    "sortPostedAsc": "Postare ↑",
    "sortDueAsc": "Data activității ↑",
    "sortDueDesc": "Data activității ↓",
    "payerBadge": "Plătitor",
    "providerBadge": "Prestator",
    "postedLabel": "Postat",
    "mealIncluded": "Masa inclusă",
    "recurringDefault": "Recurent",
    "deleteActivityTooltip": "Șterge activitatea",
    "noPostedActivities": "Nu ai activități postate în acest moment.",
    "noUpcomingActivities": "Nu ai activități viitoare.",
    "noActivitiesFound": "Nu există activități disponibile acum.",
    "today": "azi",
    "yesterday": "ieri",
    "daysAgoTemplate": "acum {days} zile",
    "perDay": "zi",
    "applyDialogTitle": "Aplicare la activitate",
    "applyDialogBody": "Vrei să confirmi aplicarea la acest anunț?",
    "removeProvider": "Elimină prestator",
    "editActivity": "Editează activitatea",
    "priceRon": "Preț (RON)",
    "durationHours": "Durată (ore)",
    "dueDate": "Data activității",
    "startTime": "Ora de start",
    "chooseDate": "Alege data",
    "chooseTime": "Alege ora",
    "mealIncludedToggle": "Cu masă inclusă",
    "recurringToggle": "Activitate recurentă",
    "recurrenceLabel": "Etichetă recurență",
    "recurrenceType": "Tip recurență",
    "recurrenceDaily": "Zilnic",
    "recurrenceWeekly": "Săptămânal",
    "recurrenceBiWeekly": "La 2 săptămâni",
    "recurrenceMonthly": "Lunar",
    "recurrenceByDays": "Pe zile selectate",
    "chooseWeekdays": "Alege zilele",
    "weekdayMon": "Luni",
    "weekdayTue": "Marți",
    "weekdayWed": "Miercuri",
    "weekdayThu": "Joi",
    "weekdayFri": "Vineri",
    "weekdaySat": "Sâmbătă",
    "weekdaySun": "Duminică",
    "youLabel": "Tu",
    "invalidData": "Date invalide. Verifică valorile introduse.",
    "activitiesLoadFailed":
        "Nu am putut încărca activitățile. Încearcă din nou.",
    "retry": "Reîncearcă",
    "help": "Ajutor",
    "logout": "Delogare",
    "showPassword": "Afișează parola",
    "settingsTabTwoFactor": "2 Factor Authenticator",
    "settingsTabSecurityVerification": "Security and Account Verification",
    "settingsTabChangePassword": "Schimbă parola",
    "settingsTabEditProfile": "Editează profilul",
    "settingsTabThemeDefault": "Tema implicită",
    "settingsTabDeleteAccount": "Șterge contul",
    "settingsChipPassword": "Parolă",
    "settingsChipTwoFactor": "2FA",
    "settingsChipSecurity": "Security",
    "settingsChipTheme": "Temă",
    "settingsChipDelete": "Șterge",
    "defaultThemeTitle": "Tema implicită după conectare",
    "defaultThemeDescription":
        "Alege tema care se aplică automat după autentificare pentru acest cont.",
    "defaultThemeLight": "Temă luminoasă",
    "defaultThemeDark": "Temă întunecată",
    "defaultThemeSaved": "Tema implicită a fost salvată.",
    "twoFactorTitle": "2 Factor Authenticator",
    "twoFactorDescription":
        "Configurarea 2FA va fi activată aici într-o iterație viitoare.",
    "enable2fa": "Activează 2FA",
    "twoFactorStatusEnabled": "2FA este activat pentru acest cont.",
    "twoFactorStatusDisabled": "2FA este dezactivat pentru acest cont.",
    "twoFactorGenerateQr": "Generează cod QR",
    "twoFactorScanHint":
        "Scanează codul în Google Authenticator, apoi introdu codul de 6 cifre.",
    "twoFactorManualKey": "Cheie manuală",
    "twoFactorCode": "Cod 2FA (6 cifre)",
    "twoFactorEnableButton": "Confirmă și activează 2FA",
    "twoFactorDisableButton": "Dezactivează 2FA",
    "twoFactorEnabledSuccess": "2FA a fost activat cu succes.",
    "twoFactorDisabledSuccess": "2FA a fost dezactivat.",
    "twoFactorInvalidCode": "Codul 2FA este invalid.",
    "twoFactorGenerateBackupCodes": "Generează backup codes",
    "twoFactorBackupCodesTitle": "Backup codes 2FA",
    "twoFactorBackupCodesDescription":
        "Salvează aceste coduri într-un loc sigur. Fiecare cod poate fi folosit o singură dată.",
    "twoFactorBackupCodesWarning":
        "Dacă le regenerezi, codurile vechi devin invalide.",
    "twoFactorBackupCodesGeneratedHint":
        "Backup codes au fost generate. Păstrează-le în siguranță.",
    "emailVerificationTitle": "Verificare cont prin e-mail",
    "emailVerificationDescription":
        "Confirmă adresa de e-mail din linkul primit. Dacă nu ai primit mesajul, retrimite emailul.",
    "emailVerificationStatusVerified": "Cont verificat",
    "emailVerificationStatusUnverified": "Cont neverificat",
    "emailVerificationResendButton": "Retrimite email de verificare",
    "emailVerificationSent": "Emailul de verificare a fost trimis.",
    "emailVerificationNotSent":
        "SMTP nu este configurat; link-ul de verificare apare doar în logurile backend.",
    "emailVerificationAlreadyVerified": "Contul este deja verificat.",
    "emailVerificationResendAfterThreeDays":
        "Emailul de verificare poate fi retrimis manual doar după 3 zile de la crearea contului.",
    "comingSoon": "În curând",
    "changePasswordTitle": "Schimbă parola",
    "currentPassword": "Parola curentă",
    "newPassword": "Parola nouă",
    "confirmNewPassword": "Confirmă parola nouă",
    "passwordChangeSoon":
        "Endpoint-ul de schimbare parolă va fi adăugat în curând.",
    "deleteAccountTitle": "Șterge contul",
    "deleteAccountDescription":
        "Această acțiune este permanentă și va fi protejată prin verificare suplimentară.",
    "deleteAccountButton": "Șterge contul",
    "deleteAccountDialogTitle": "Confirmare ștergere cont",
    "deleteAccountDialogDescription":
        "Introdu emailul contului și parola de două ori pentru confirmare.",
    "confirmEmail": "Confirmă emailul",
    "confirmPasswordAgain": "Confirmă parola încă o dată",
    "deleteAccountEmailMismatch":
        "Emailul introdus nu corespunde contului curent.",
    "deleteAccountPasswordMismatch": "Parolele nu coincid.",
    "deleteAccountFlowSoon": "Fluxul de ștergere cont va fi activat în curând.",
    "delete": "Șterge",
    "achievementNoBadges": "Niciun badge deblocat momentan",
    "achievementUnlockedNone": "Nu exista nici un achivement deblocat",
    "achievementStatusUnlocked": "Deblocat",
    "achievementStatusAvailable": "Se poate debloca",
    "achievementStatusUnavailable": "Indisponibil",
    "badgeFounderTitle": "Founder",
    "badgeFounderDescription":
        "Membru fondator CareerSuitUp. Badge acordat conturilor fondatoare.",
    "badgeTwoFactorTitle": "2FA Enabled",
    "badgeTwoFactorDescription":
        "Ai activat autentificarea în 2 pași și contul tău este mai sigur.",
    "educationHighSchool": "Liceu",
    "educationHighSchoolCompleted": "Liceu absolvit",
    "educationPostSecondaryLabel": "Școală postliceală",
    "educationPostSecondary": "Postliceală",
    "educationBachelor": "Licență",
    "educationMaster": "Master",
    "educationDoctorate": "Doctorat",
    "educationUniversityLabel": "Universitate",
    "educationFacultySpecializationOptional":
        "Facultate / Specializare (opțional)",
    "skillsLanguages": "Limbi",
    "skillsSoft": "Soft Skills",
    "skillsHard": "Hard Skills",
    "addLanguageSkill": "Adaugă limbă",
    "addSoftSkill": "Adaugă soft skill",
    "addHardSkill": "Adaugă hard skill",
    "skillNameLabel": "Competență",
    "languageSkillNameLabel": "Limbă",
    "softSkillNameLabel": "Soft skill",
    "hardSkillNameLabel": "Hard skill",
    "languageSkillPlaceholder": "Caută o limbă",
    "softSkillPlaceholder": "Caută un soft skill",
    "hardSkillPlaceholder": "Caută un hard skill",
    "skillScoreLabel": "Notă (1-10)",
    "skillsEmptyState": "Nu ai adăugat competențe încă.",
    "skillsSidebarHint": "Subcategorii competențe",
    "monthName01": "Ianuarie",
    "monthName02": "Februarie",
    "monthName03": "Martie",
    "monthName04": "Aprilie",
    "monthName05": "Mai",
    "monthName06": "Iunie",
    "monthName07": "Iulie",
    "monthName08": "August",
    "monthName09": "Septembrie",
    "monthName10": "Octombrie",
    "monthName11": "Noiembrie",
    "monthName12": "Decembrie",
    "externalLinkDialogTitle": "Deschidere link extern",
    "externalLinkDialogDescription":
        "Urmează să părăsești aplicația și să deschizi un link extern.",
    "continueAction": "Continuă",
  },
  "EN": {
    "login": "Login",
    "register": "Register",
    "email": "E-mail",
    "title": "Title",
    "description": "Description",
    "password": "Password",
    "confirm": "Confirm Password",
    "remember": "Remember my credentials",
    "forgot": "I forgot my password",
    "user": "User",
    "company": "Company",
    "companyName": "Company Name",
    "first": "First Name",
    "last": "Last Name",
    "passMismatch": "Passwords do not match!",
    "lower": "At least a lowercase letter",
    "upper": "At least an uppercase letter",
    "number": "At least a digit",
    "special": "At least a special character",
    "emailInfo":
        "Please insert a valid e-mail address to send you the login credentials.",
    "send": "Send",
    "appName": "CareerSuitUp",
    "leftHeadingLogin": "Enter your career command center",
    "leftHeadingRegister": "Build your professional identity for tomorrow",
    "leftSubtitle":
        "Smart recruitment focused on skills and measurable outcomes",
    "leftDescriptionLogin":
        "Activate your profile, track relevant opportunities, and connect fast with verified employers.",
    "leftDescriptionRegister":
        "Create your account and join an ecosystem where candidates and companies collaborate transparently in real time.",
    "leftSignalRealtime": "Real-time recommendations",
    "leftSignalTrust": "Verified profiles",
    "leftSignalPrecision": "Precision skill-to-job matching",
    "gdprTitle": "Privacy Policy and Data Processing",
    "gdprDescription":
        "By continuing to register, you confirm that you have read and understood the privacy policy and consent to the processing of personal data in accordance with GDPR.",
    "gdprLink": "Read the complete privacy policy",
    "gdprLinkPlaceholder": "Opening official GDPR document...",
    "gdprConsent":
        "I agree to the processing of my personal data according to GDPR",
    "cancel": "Cancel",
    "save": "Save",
    "confirmAction": "Confirm",
    "accept": "Accept",
    "back": "Back",
    "next": "Continue",
    "country": "Country",
    "userLocationSection": "Location details",
    "hrFirstName": "HR Representative First Name",
    "hrLastName": "HR Representative Last Name",
    "hrEmail": "HR Representative Email",
    "hrContactSection": "Contact details for HR representative",
    "userProfileSection": "Candidate profile completion",
    "phone": "Phone",
    "county": "County",
    "city": "City",
    "professionalTitle": "Professional title",
    "profileSummary": "Profile summary",
    "socialLinks": "Main links",
    "experienceSection": "Experience",
    "skillsSection": "Skills",
    "educationSection": "Education",
    "projectsSection": "Projects",
    "activityFeed": "Activity Feed",
    "activityPostLabel": "Post",
    "activityEmptyState": "There are no posts yet.",
    "postPlaceholder": "What would you like to share?",
    "postAction": "Post",
    "editPost": "Edit post",
    "deletePost": "Delete post",
    "addEmoji": "Add emoji",
    "addSticker": "Add sticker",
    "addAttachment": "Add attachment",
    "pickEmoji": "Pick an emoji",
    "pickSticker": "Pick a sticker",
    "activityComments": "Comments",
    "activityCommentPlaceholder": "Write a comment...",
    "commentAction": "Comment",
    "activityPostOwnerOnly":
        "Only this profile owner can publish posts here. You can comment on existing posts.",
    "emojiCategorySmileys": "Smileys",
    "emojiCategoryWork": "Work",
    "emojiCategoryCelebrate": "Celebrate",
    "emojiCategoryPeople": "People",
    "stickerCategoryBusiness": "Business",
    "stickerCategoryMotivation": "Motivation",
    "stickerCategoryReactions": "Reactions",
    "stickerCategoryStatus": "Status",
    "clear": "Clear",
    "present": "Present",
    "professionalStatus": "Professional status",
    "professionalStatusOpenToWork": "Open to Work",
    "professionalStatusHired": "Hired",
    "professionalStatusNotAvailable": "Not available",
    "yearsExperience": "Years of experience",
    "experienceMaxThreeHint": "You can add up to 5 work experiences.",
    "experienceEmptyState": "You have not added work experiences yet.",
    "experienceItemLabel": "Experience",
    "experienceShortDescription": "Short description",
    "startMonth": "Start month",
    "startYear": "Start year",
    "endMonth": "End month",
    "endYear": "End year",
    "invalidEndDate": "End date must be after the start date",
    "experienceCurrentRole": "I currently work here",
    "addExperienceItem": "Add experience",
    "educationMaxThreeHint": "You can add up to 5 education entries.",
    "educationEmptyState": "You have not added education entries yet.",
    "educationItemLabel": "Education",
    "universityName": "University",
    "educationCurrentRole": "I currently study here",
    "addEducationItem": "Add education",
    "projectsMaxHint": "You can add up to 10 projects.",
    "projectsEmptyState": "You have not added projects yet.",
    "projectItemLabel": "Project",
    "projectTitleLabel": "Project title",
    "projectDescriptionLabel": "Project description",
    "projectGithubLabel": "GitHub link (optional)",
    "projectCurrentLabel": "Ongoing project",
    "addProjectItem": "Add project",
    "educationLevel": "Education level",
    "educationFormLabel": "Education level",
    "educationInstitutionLabel": "Educational institution",
    "lastEducationInstitution": "Last educational institution completed",
    "specialization": "Specialization",
    "gender": "Gender",
    "genderMale": "Male",
    "genderFemale": "Female",
    "birthDate": "Birth date",
    "pickBirthDate": "Choose birth date",
    "accountCreatedDate": "Account creation date",
    "accountCreatedTime": "Account creation time",
    "cvAttachmentSection": "CV attachment",
    "uploadCv": "Upload CV (PDF/DOC/DOCX)",
    "cvAttachmentSelected": "Selected file",
    "cvAttachmentMissing": "CV attachment is required",
    "selectedValueMissing": "The selected value does not exist in the list",
    "completeAllFields": "Please complete all required fields",
    "loginEmailNotFound":
        "No account exists yet for the specified email address.",
    "loginWrongPassword":
        "The password entered is incorrect. Please try logging in again.",
    "loginRetryIn": "You can try again in",
    "loginGenericError": "An authentication error occurred.",
    "loginTwoFactorRequired": "Enter the authenticator code to continue.",
    "loginTwoFactorInvalid": "The two-factor authentication code is invalid.",
    "loginTwoFactorDialogTitle": "2FA authentication code",
    "loginTwoFactorDialogDescription":
        "Enter the code from Google Authenticator.",
    "registerSuccessTitle": "Account created successfully",
    "registerSuccessMessage": "Your account has been created successfully.",
    "registerEmailAlreadyExists":
        "An account is already associated with this email address.",
    "ok": "OK",
    "profile": "Profile",
    "home": "Home",
    "achievements": "Achievements",
    "settings": "Settings",
    "accountDetails": "Account details",
    "locationDetails": "Location details",
    "profileDetails": "Profile",
    "attachments": "Attachments",
    "companyDetails": "Company details",
    "hrDetails": "HR contact",
    "saveChanges": "Save",
    "saveAll": "Save all",
    "previewProfile": "Preview draft profile",
    "settingsDraftPending":
        "You have unsaved changes. You can preview the profile before saving.",
    "settingsDraftSynced": "There are no unsaved changes.",
    "profilePreviewDraftTitle": "Profile preview (draft)",
    "profilePreviewDraftDescription":
        "This is how the public profile will look after saving your changes.",
    "profilePreviewNoPublicFields":
        "No public fields are visible with the current visibility settings.",
    "settingsSubcategoryVisibilityHint":
        "Open this subcategory and set lock/unlock for the fields shown on profile.",
    "visibility": "Visibility",
    "public": "Public",
    "private": "Private",
    "cvAvailable": "CV available",
    "cvNotAvailable": "CV missing",
    "profilePhoto": "Profile photo",
    "uploadProfilePhoto": "Upload profile photo",
    "photoSet": "Set",
    "photoMissing": "Missing",
    "message": "Message",
    "messages": "Messages",
    "notifications": "Notifications",
    "downloadCvAction": "Download CV",
    "searchCandidatesJobs": "Search candidates, jobs...",
    "searchInProfiles": "Search text in Profiles",
    "searchInJobs": "Search text in Jobs",
    "searchInActivities": "Search text in Activities",
    "searchAction": "Search",
    "closeSearch": "Close search",
    "searchSelfBadge": "Me",
    "searchNoResults": "No profiles found for this query.",
    "searchFiltersLabel": "Search filters:",
    "searchFilterAll": "All fields",
    "searchFilterName": "First + last name",
    "searchFilterEmail": "Email",
    "searchFilterJobTitle": "Job title",
    "homeTileActivities": "Activities",
    "homeTileActivitiesSubtitle": "Explore the community",
    "homeTileJobs": "Jobs",
    "homeTileJobsSubtitle": "Discover new opportunities",
    "homeCommunityTitle": "Latest from the community",
    "homeCommunityPost1": "Excited to start my new job! #NewBeginnings",
    "homeCommunityPost2": "We're hiring! Looking for a Marketing Specialist.",
    "homeCommunityPost3": "Great networking night! Met amazing people.",
    "homeActivitiesPlaceholder": "Activities page is being prepared.",
    "homeJobsPlaceholder": "Jobs page is being prepared.",
    "activitiesTitle": "Activities",
    "addActivity": "Add activity",
    "asPayer": "As payer",
    "asProvider": "As provider",
    "postedActivities": "Posted activities",
    "upcomingEvents": "Upcoming events",
    "allActivities": "Activities",
    "recurringActivities": "Recurring activities",
    "oneTimeActivities": "One-time activities",
    "sortPostedDesc": "Posted ↓",
    "sortPostedAsc": "Posted ↑",
    "sortDueAsc": "Due date ↑",
    "sortDueDesc": "Due date ↓",
    "payerBadge": "Payer",
    "providerBadge": "Provider",
    "postedLabel": "Posted",
    "mealIncluded": "Meal included",
    "recurringDefault": "Recurring",
    "deleteActivityTooltip": "Delete activity",
    "noPostedActivities": "You have no posted activities right now.",
    "noUpcomingActivities": "You have no upcoming activities.",
    "noActivitiesFound": "No activities available right now.",
    "today": "today",
    "yesterday": "yesterday",
    "daysAgoTemplate": "{days} days ago",
    "perDay": "day",
    "applyDialogTitle": "Apply for activity",
    "applyDialogBody": "Do you want to confirm applying for this post?",
    "removeProvider": "Remove provider",
    "editActivity": "Edit activity",
    "priceRon": "Price (RON)",
    "durationHours": "Duration (hours)",
    "dueDate": "Due date",
    "startTime": "Start time",
    "chooseDate": "Choose date",
    "chooseTime": "Choose time",
    "mealIncludedToggle": "Meal included",
    "recurringToggle": "Recurring activity",
    "recurrenceLabel": "Recurrence label",
    "recurrenceType": "Recurrence type",
    "recurrenceDaily": "Daily",
    "recurrenceWeekly": "Weekly",
    "recurrenceBiWeekly": "Every 2 weeks",
    "recurrenceMonthly": "Monthly",
    "recurrenceByDays": "Selected weekdays",
    "chooseWeekdays": "Choose weekdays",
    "weekdayMon": "Mon",
    "weekdayTue": "Tue",
    "weekdayWed": "Wed",
    "weekdayThu": "Thu",
    "weekdayFri": "Fri",
    "weekdaySat": "Sat",
    "weekdaySun": "Sun",
    "youLabel": "You",
    "invalidData": "Invalid data. Please review the values.",
    "activitiesLoadFailed": "Could not load activities. Please try again.",
    "retry": "Retry",
    "help": "Help",
    "logout": "Log out",
    "showPassword": "Show password",
    "settingsTabTwoFactor": "2 Factor Authenticator",
    "settingsTabSecurityVerification": "Security and Account Verification",
    "settingsTabChangePassword": "Change Password",
    "settingsTabEditProfile": "Edit Profile Data",
    "settingsTabThemeDefault": "Default theme",
    "settingsTabDeleteAccount": "Delete Account",
    "settingsChipPassword": "Password",
    "settingsChipTwoFactor": "2FA",
    "settingsChipSecurity": "Security",
    "settingsChipTheme": "Theme",
    "settingsChipDelete": "Delete",
    "defaultThemeTitle": "Default theme after login",
    "defaultThemeDescription":
        "Choose the theme that is automatically applied after authentication for this account.",
    "defaultThemeLight": "Light theme",
    "defaultThemeDark": "Dark theme",
    "defaultThemeSaved": "Default theme has been saved.",
    "twoFactorTitle": "2 Factor Authenticator",
    "twoFactorDescription":
        "2FA setup will be enabled here in a next iteration.",
    "enable2fa": "Enable 2FA",
    "twoFactorStatusEnabled": "2FA is enabled for this account.",
    "twoFactorStatusDisabled": "2FA is disabled for this account.",
    "twoFactorGenerateQr": "Generate QR code",
    "twoFactorScanHint":
        "Scan the code in Google Authenticator, then enter the 6-digit code.",
    "twoFactorManualKey": "Manual key",
    "twoFactorCode": "2FA code (6 digits)",
    "twoFactorEnableButton": "Confirm and enable 2FA",
    "twoFactorDisableButton": "Disable 2FA",
    "twoFactorEnabledSuccess": "2FA has been enabled successfully.",
    "twoFactorDisabledSuccess": "2FA has been disabled.",
    "twoFactorInvalidCode": "The 2FA code is invalid.",
    "twoFactorGenerateBackupCodes": "Generate backup codes",
    "twoFactorBackupCodesTitle": "2FA backup codes",
    "twoFactorBackupCodesDescription":
        "Save these codes in a safe place. Each code can be used only once.",
    "twoFactorBackupCodesWarning":
        "If you regenerate them, previous codes become invalid.",
    "twoFactorBackupCodesGeneratedHint":
        "Backup codes were generated. Keep them safe.",
    "emailVerificationTitle": "Email account verification",
    "emailVerificationDescription":
        "Confirm your email address using the link you received. If you didn't receive it, resend the verification email.",
    "emailVerificationStatusVerified": "Account verified",
    "emailVerificationStatusUnverified": "Account not verified",
    "emailVerificationResendButton": "Resend verification email",
    "emailVerificationSent": "Verification email has been sent.",
    "emailVerificationNotSent":
        "SMTP is not configured; verification link is only logged on backend.",
    "emailVerificationAlreadyVerified": "Account is already verified.",
    "emailVerificationResendAfterThreeDays":
        "The verification email can be manually resent only after 3 days from account creation.",
    "comingSoon": "Coming soon",
    "changePasswordTitle": "Change Password",
    "currentPassword": "Current password",
    "newPassword": "New password",
    "confirmNewPassword": "Confirm new password",
    "passwordChangeSoon": "Password change endpoint is coming soon.",
    "deleteAccountTitle": "Delete Account",
    "deleteAccountDescription":
        "This action is permanent and will be protected by additional verification.",
    "deleteAccountButton": "Delete account",
    "deleteAccountDialogTitle": "Delete account confirmation",
    "deleteAccountDialogDescription":
        "Enter your account email and password twice to confirm.",
    "confirmEmail": "Confirm email",
    "confirmPasswordAgain": "Confirm password again",
    "deleteAccountEmailMismatch":
        "The entered email does not match the current account.",
    "deleteAccountPasswordMismatch": "Passwords do not match.",
    "deleteAccountFlowSoon": "Delete account flow will be enabled soon.",
    "delete": "Delete",
    "achievementNoBadges": "No badges unlocked yet",
    "achievementUnlockedNone": "No achievements unlocked",
    "achievementStatusUnlocked": "Unlocked",
    "achievementStatusAvailable": "Can be unlocked",
    "achievementStatusUnavailable": "Unavailable",
    "badgeFounderTitle": "Founder",
    "badgeFounderDescription":
        "CareerSuitUp founding member badge, assigned to founder accounts.",
    "badgeTwoFactorTitle": "2FA Enabled",
    "badgeTwoFactorDescription":
        "You enabled two-factor authentication and improved account security.",
    "educationHighSchool": "High School",
    "educationHighSchoolCompleted": "Completed high school",
    "educationPostSecondaryLabel": "Post-secondary school",
    "educationPostSecondary": "Post-secondary",
    "educationBachelor": "Bachelor",
    "educationMaster": "Master",
    "educationDoctorate": "Doctorate",
    "educationUniversityLabel": "University",
    "educationFacultySpecializationOptional":
        "Faculty / Specialization (optional)",
    "skillsLanguages": "Languages",
    "skillsSoft": "Soft Skills",
    "skillsHard": "Hard Skills",
    "addLanguageSkill": "Add language",
    "addSoftSkill": "Add soft skill",
    "addHardSkill": "Add hard skill",
    "skillNameLabel": "Skill",
    "languageSkillNameLabel": "Language",
    "softSkillNameLabel": "Soft skill",
    "hardSkillNameLabel": "Hard skill",
    "languageSkillPlaceholder": "Search a language",
    "softSkillPlaceholder": "Search a soft skill",
    "hardSkillPlaceholder": "Search a hard skill",
    "skillScoreLabel": "Score (1-10)",
    "skillsEmptyState": "You have not added skills yet.",
    "skillsSidebarHint": "Skills subcategories",
    "monthName01": "January",
    "monthName02": "February",
    "monthName03": "March",
    "monthName04": "April",
    "monthName05": "May",
    "monthName06": "June",
    "monthName07": "July",
    "monthName08": "August",
    "monthName09": "September",
    "monthName10": "October",
    "monthName11": "November",
    "monthName12": "December",
    "externalLinkDialogTitle": "Open external link",
    "externalLinkDialogDescription":
        "You are about to leave the app and open an external link.",
    "continueAction": "Continue",
  },
};

String _activeLang = 'RO';

void setActiveLanguage(String lang) {
  if (texts.containsKey(lang)) {
    _activeLang = lang;
  }
}

String t(String lang, String key) {
  final fallbackLang = texts.containsKey('EN') ? 'EN' : texts.keys.first;
  final resolvedLang = texts.containsKey(lang)
      ? lang
      : (texts.containsKey(_activeLang) ? _activeLang : fallbackLang);
  final langMap = texts[resolvedLang] ?? texts[fallbackLang]!;
  return langMap[key] ?? texts[fallbackLang]?[key] ?? key;
}

List<String> supportedLanguages() => texts.keys.toList(growable: false);
