Map<String, Map<String, String>> texts = {
  "RO": {
    "login": "Conectare",
    "register": "Înregistrare",
    "email": "E-mail",
    "password": "Parolă",
    "confirm": "Confirmare Parola",
    "remember": "Ține minte credențialele",
    "forgot": "Mi-am uitat parola",
    "user": "Utilizator",
    "company": "Companie",
    "companyName": "Nume companie",
    "first": "Prenume",
    "last": "Nume",
    "passMismatch": "Parolele nu coincid!",
    "lower": "Cel puțin o literă mică",
    "upper": "Cel puțin o literă mare",
    "number": "Cel puțin o cifră",
    "special": "Cel puțin un caracter special",
    "emailInfo":
        "Vă rugăm să introduceți o adresă de e-mail validă pentru a vă putea trimite credențialele de conectare.",
    "send": "Trimite",
    "appName": "CareerSuitUp",
    "leftHeadingLogin": "Bine ai revenit pe platforma noastră de recrutare",
    "leftHeadingRegister": "Alătură-te comunității noastre de recrutare",
    "leftSubtitle":
        "Conectează candidați și companii într-un mod simplu și eficient",
    "gdprTitle": "Politica de Confidențialitate și Prelucrarea Datelor",
    "gdprDescription":
        "Prin continuarea înregistrării, confirmi că ți-ai citit și înțeles politica de confidențialitate și consimți prelucrarea datelor personale în conformitate cu GDPR.",
    "gdprLink": "Citește política de confidențialitate completă",
    "gdprLinkPlaceholder": "Deschiderea documentului oficial GDPR...",
    "gdprConsent":
        "Sunt de acord cu prelucrarea datelor mele personale conform GDPR",
    "cancel": "Anulare",
    "accept": "Accept",
    "back": "Înapoi",
    "next": "Continuă",
    "country": "Țara",
    "userLocationSection": "Date de localizare",
    "hrFirstName": "Prenumele reprezentantului HR",
    "hrLastName": "Numele reprezentantului HR",
    "hrEmail": "Email-ul reprezentantului HR",
    "hrContactSection": "Date de contact pentru persoana HR",
    "idAttachmentSection": "Atașamente verificare identitate",
    "uploadIdImage": "Încarcă poză carte de identitate",
    "idAttachmentSelected": "Fișier selectat",
    "idAttachmentMissing": "Atașament CI obligatoriu",
    "userProfileSection": "Completare profil candidat",
    "phone": "Telefon",
    "county": "Județ",
    "city": "Localitate",
    "professionalTitle": "Titlu profesional",
    "yearsExperience": "Ani de experiență",
    "educationLevel": "Ultima formă de învățământ absolvită",
    "lastEducationInstitution": "Ultima unitate de învățământ absolvită",
    "gender": "Gen",
    "genderMale": "Masculin",
    "genderFemale": "Feminin",
    "birthDate": "Data nașterii",
    "pickBirthDate": "Alege data nașterii",
    "cvAttachmentSection": "Atașament CV",
    "uploadCv": "Încarcă CV (PDF/DOC/DOCX)",
    "cvAttachmentMissing": "Atașament CV obligatoriu",
    "selectedValueMissing": "Valoarea selectată nu există în listă",
    "completeAllFields": "Completează toate câmpurile obligatorii",
    "loginEmailNotFound":
        "Nu există încă un cont creat pentru adresa de e-mail specificată.",
    "loginWrongPassword":
        "Parola introdusă nu este corectă. Vă rugăm reîncercați logarea.",
    "loginRetryIn": "Poți încerca din nou în",
    "loginGenericError": "A apărut o eroare la autentificare.",
    "loginTwoFactorRequired":
        "Introdu codul din aplicația de autentificare pentru a continua.",
    "loginTwoFactorInvalid":
        "Codul de autentificare cu doi factori nu este valid.",
    "loginTwoFactorDialogTitle": "Cod de autentificare 2FA",
    "loginTwoFactorDialogDescription":
        "Introdu codul din Google Authenticator.",
    "registerSuccessTitle": "Cont creat cu succes",
    "registerSuccessMessage": "Contul a fost creat cu succes.",
    "registerEmailAlreadyExists":
        "Exista deja un cont asociat acestei adrese de e-mail.",
    "ok": "OK",
    "profile": "Profil",
    "home": "Home",
    "achievements": "Achievements",
    "settings": "Setări",
    "accountDetails": "Date cont",
    "locationDetails": "Date de localizare",
    "profileDetails": "Profil",
    "attachments": "Atașamente",
    "companyDetails": "Date companie",
    "hrDetails": "Contact HR",
    "saveChanges": "Salvează",
    "saveAll": "Salvează tot",
    "previewProfile": "Vezi profilul public",
    "visibility": "Vizibilitate",
    "public": "Public",
    "private": "Privat",
    "cvAvailable": "CV disponibil",
    "cvNotAvailable": "CV lipsă",
    "profilePhoto": "Poză de profil",
    "uploadProfilePhoto": "Încarcă poză de profil",
    "photoSet": "Setată",
    "photoMissing": "Lipsă",
    "help": "Ajutor",
    "logout": "Delogare",
    "showPassword": "Afișează parola",
    "settingsTabTwoFactor": "2 Factor Authenticator",
    "settingsTabSecurityVerification": "Security and Account Verification",
    "settingsTabChangePassword": "Schimbă parola",
    "settingsTabEditProfile": "Editează profilul",
    "settingsTabThemeDefault": "Tema implicită",
    "settingsTabDeleteAccount": "Șterge contul",
    "settingsChipPassword": "Parolă",
    "settingsChipTwoFactor": "2FA",
    "settingsChipSecurity": "Security",
    "settingsChipTheme": "Temă",
    "settingsChipDelete": "Șterge",
    "defaultThemeTitle": "Tema implicită după conectare",
    "defaultThemeDescription":
        "Alege tema care se aplică automat după autentificare pentru acest cont.",
    "defaultThemeLight": "Temă luminoasă",
    "defaultThemeDark": "Temă întunecată",
    "defaultThemeSaved": "Tema implicită a fost salvată.",
    "twoFactorTitle": "2 Factor Authenticator",
    "twoFactorDescription":
        "Configurarea 2FA va fi activată aici într-o iterație viitoare.",
    "enable2fa": "Activează 2FA",
    "twoFactorStatusEnabled": "2FA este activat pentru acest cont.",
    "twoFactorStatusDisabled": "2FA este dezactivat pentru acest cont.",
    "twoFactorGenerateQr": "Generează cod QR",
    "twoFactorScanHint":
        "Scanează codul în Google Authenticator, apoi introdu codul de 6 cifre.",
    "twoFactorManualKey": "Cheie manuală",
    "twoFactorCode": "Cod 2FA (6 cifre)",
    "twoFactorEnableButton": "Confirmă și activează 2FA",
    "twoFactorDisableButton": "Dezactivează 2FA",
    "twoFactorEnabledSuccess": "2FA a fost activat cu succes.",
    "twoFactorDisabledSuccess": "2FA a fost dezactivat.",
    "twoFactorInvalidCode": "Codul 2FA este invalid.",
    "twoFactorGenerateBackupCodes": "Generează backup codes",
    "twoFactorBackupCodesTitle": "Backup codes 2FA",
    "twoFactorBackupCodesDescription":
        "Salvează aceste coduri într-un loc sigur. Fiecare cod poate fi folosit o singură dată.",
    "twoFactorBackupCodesWarning":
        "Dacă le regenerezi, codurile vechi devin invalide.",
    "twoFactorBackupCodesGeneratedHint":
        "Backup codes au fost generate. Păstrează-le în siguranță.",
    "emailVerificationTitle": "Verificare cont prin e-mail",
    "emailVerificationDescription":
        "Confirmă adresa de e-mail din linkul primit. Dacă nu ai primit mesajul, retrimite emailul.",
    "emailVerificationStatusVerified": "Cont verificat",
    "emailVerificationStatusUnverified": "Cont neverificat",
    "emailVerificationResendButton": "Retrimite email de verificare",
    "emailVerificationSent": "Emailul de verificare a fost trimis.",
    "emailVerificationNotSent":
        "SMTP nu este configurat; link-ul de verificare apare doar în logurile backend.",
    "emailVerificationAlreadyVerified": "Contul este deja verificat.",
    "emailVerificationResendAfterThreeDays":
        "Emailul de verificare poate fi retrimis manual doar după 3 zile de la crearea contului.",
    "comingSoon": "În curând",
    "changePasswordTitle": "Schimbă parola",
    "currentPassword": "Parola curentă",
    "newPassword": "Parola nouă",
    "confirmNewPassword": "Confirmă parola nouă",
    "passwordChangeSoon":
        "Endpoint-ul de schimbare parolă va fi adăugat în curând.",
    "deleteAccountTitle": "Șterge contul",
    "deleteAccountDescription":
        "Această acțiune este permanentă și va fi protejată prin verificare suplimentară.",
    "deleteAccountButton": "Șterge contul",
    "deleteAccountDialogTitle": "Confirmare ștergere cont",
    "deleteAccountDialogDescription":
        "Introdu emailul contului și parola de două ori pentru confirmare.",
    "confirmEmail": "Confirmă emailul",
    "confirmPasswordAgain": "Confirmă parola încă o dată",
    "deleteAccountEmailMismatch":
        "Emailul introdus nu corespunde contului curent.",
    "deleteAccountPasswordMismatch": "Parolele nu coincid.",
    "deleteAccountFlowSoon": "Fluxul de ștergere cont va fi activat în curând.",
    "achievementNoBadges": "Niciun badge deblocat momentan",
    "achievementUnlockedNone": "Nu exista nici un achivement deblocat",
    "achievementStatusUnlocked": "Deblocat",
    "achievementStatusAvailable": "Se poate debloca",
    "achievementStatusUnavailable": "Indisponibil",
    "badgeFounderTitle": "Founder",
    "badgeFounderDescription":
        "Membru fondator CareerSuitUp. Badge acordat conturilor fondatoare.",
    "badgeTwoFactorTitle": "2FA Enabled",
    "badgeTwoFactorDescription":
        "Ai activat autentificarea în 2 pași și contul tău este mai sigur.",
    "educationHighSchool": "Liceu",
    "educationPostSecondary": "Postliceală",
    "educationBachelor": "Licență",
    "educationMaster": "Master",
    "educationDoctorate": "Doctorat",
  },
  "EN": {
    "login": "Login",
    "register": "Register",
    "email": "E-mail",
    "password": "Password",
    "confirm": "Confirm Password",
    "remember": "Remember my credentials",
    "forgot": "I forgot my password",
    "user": "User",
    "company": "Company",
    "companyName": "Company Name",
    "first": "First Name",
    "last": "Last Name",
    "passMismatch": "Passwords do not match!",
    "lower": "At least a lowercase letter",
    "upper": "At least an uppercase letter",
    "number": "At least a digit",
    "special": "At least a special character",
    "emailInfo":
        "Please insert a valid e-mail address to send you the login credentials.",
    "send": "Send",
    "appName": "CareerSuitUp",
    "leftHeadingLogin": "Welcome back to your hiring platform",
    "leftHeadingRegister": "Join our hiring community",
    "leftSubtitle":
        "Connect candidates and companies in a simple, efficient way",
    "gdprTitle": "Privacy Policy and Data Processing",
    "gdprDescription":
        "By continuing to register, you confirm that you have read and understood the privacy policy and consent to the processing of personal data in accordance with GDPR.",
    "gdprLink": "Read the complete privacy policy",
    "gdprLinkPlaceholder": "Opening official GDPR document...",
    "gdprConsent":
        "I agree to the processing of my personal data according to GDPR",
    "cancel": "Cancel",
    "accept": "Accept",
    "back": "Back",
    "next": "Continue",
    "country": "Country",
    "userLocationSection": "Location details",
    "hrFirstName": "HR Representative First Name",
    "hrLastName": "HR Representative Last Name",
    "hrEmail": "HR Representative Email",
    "hrContactSection": "Contact details for HR representative",
    "idAttachmentSection": "Identity verification attachments",
    "uploadIdImage": "Upload ID card image",
    "idAttachmentSelected": "Selected file",
    "idAttachmentMissing": "ID attachment is required",
    "userProfileSection": "Candidate profile completion",
    "phone": "Phone",
    "county": "County",
    "city": "City",
    "professionalTitle": "Professional title",
    "yearsExperience": "Years of experience",
    "educationLevel": "Highest education level completed",
    "lastEducationInstitution": "Last educational institution completed",
    "gender": "Gender",
    "genderMale": "Male",
    "genderFemale": "Female",
    "birthDate": "Birth date",
    "pickBirthDate": "Choose birth date",
    "cvAttachmentSection": "CV attachment",
    "uploadCv": "Upload CV (PDF/DOC/DOCX)",
    "cvAttachmentMissing": "CV attachment is required",
    "selectedValueMissing": "The selected value does not exist in the list",
    "completeAllFields": "Please complete all required fields",
    "loginEmailNotFound":
        "No account exists yet for the specified email address.",
    "loginWrongPassword":
        "The password entered is incorrect. Please try logging in again.",
    "loginRetryIn": "You can try again in",
    "loginGenericError": "An authentication error occurred.",
    "loginTwoFactorRequired": "Enter the authenticator code to continue.",
    "loginTwoFactorInvalid": "The two-factor authentication code is invalid.",
    "loginTwoFactorDialogTitle": "2FA authentication code",
    "loginTwoFactorDialogDescription":
        "Enter the code from Google Authenticator.",
    "registerSuccessTitle": "Account created successfully",
    "registerSuccessMessage": "Your account has been created successfully.",
    "registerEmailAlreadyExists":
        "An account is already associated with this email address.",
    "ok": "OK",
    "profile": "Profile",
    "home": "Home",
    "achievements": "Achievements",
    "settings": "Settings",
    "accountDetails": "Account details",
    "locationDetails": "Location details",
    "profileDetails": "Profile",
    "attachments": "Attachments",
    "companyDetails": "Company details",
    "hrDetails": "HR contact",
    "saveChanges": "Save",
    "saveAll": "Save all",
    "previewProfile": "Preview public profile",
    "visibility": "Visibility",
    "public": "Public",
    "private": "Private",
    "cvAvailable": "CV available",
    "cvNotAvailable": "CV missing",
    "profilePhoto": "Profile photo",
    "uploadProfilePhoto": "Upload profile photo",
    "photoSet": "Set",
    "photoMissing": "Missing",
    "help": "Help",
    "logout": "Log out",
    "showPassword": "Show password",
    "settingsTabTwoFactor": "2 Factor Authenticator",
    "settingsTabSecurityVerification": "Security and Account Verification",
    "settingsTabChangePassword": "Change Password",
    "settingsTabEditProfile": "Edit Profile Data",
    "settingsTabThemeDefault": "Default theme",
    "settingsTabDeleteAccount": "Delete Account",
    "settingsChipPassword": "Password",
    "settingsChipTwoFactor": "2FA",
    "settingsChipSecurity": "Security",
    "settingsChipTheme": "Theme",
    "settingsChipDelete": "Delete",
    "defaultThemeTitle": "Default theme after login",
    "defaultThemeDescription":
        "Choose the theme that is automatically applied after authentication for this account.",
    "defaultThemeLight": "Light theme",
    "defaultThemeDark": "Dark theme",
    "defaultThemeSaved": "Default theme has been saved.",
    "twoFactorTitle": "2 Factor Authenticator",
    "twoFactorDescription":
        "2FA setup will be enabled here in a next iteration.",
    "enable2fa": "Enable 2FA",
    "twoFactorStatusEnabled": "2FA is enabled for this account.",
    "twoFactorStatusDisabled": "2FA is disabled for this account.",
    "twoFactorGenerateQr": "Generate QR code",
    "twoFactorScanHint":
        "Scan the code in Google Authenticator, then enter the 6-digit code.",
    "twoFactorManualKey": "Manual key",
    "twoFactorCode": "2FA code (6 digits)",
    "twoFactorEnableButton": "Confirm and enable 2FA",
    "twoFactorDisableButton": "Disable 2FA",
    "twoFactorEnabledSuccess": "2FA has been enabled successfully.",
    "twoFactorDisabledSuccess": "2FA has been disabled.",
    "twoFactorInvalidCode": "The 2FA code is invalid.",
    "twoFactorGenerateBackupCodes": "Generate backup codes",
    "twoFactorBackupCodesTitle": "2FA backup codes",
    "twoFactorBackupCodesDescription":
        "Save these codes in a safe place. Each code can be used only once.",
    "twoFactorBackupCodesWarning":
        "If you regenerate them, previous codes become invalid.",
    "twoFactorBackupCodesGeneratedHint":
        "Backup codes were generated. Keep them safe.",
    "emailVerificationTitle": "Email account verification",
    "emailVerificationDescription":
        "Confirm your email address using the link you received. If you didn't receive it, resend the verification email.",
    "emailVerificationStatusVerified": "Account verified",
    "emailVerificationStatusUnverified": "Account not verified",
    "emailVerificationResendButton": "Resend verification email",
    "emailVerificationSent": "Verification email has been sent.",
    "emailVerificationNotSent":
        "SMTP is not configured; verification link is only logged on backend.",
    "emailVerificationAlreadyVerified": "Account is already verified.",
    "emailVerificationResendAfterThreeDays":
        "The verification email can be manually resent only after 3 days from account creation.",
    "comingSoon": "Coming soon",
    "changePasswordTitle": "Change Password",
    "currentPassword": "Current password",
    "newPassword": "New password",
    "confirmNewPassword": "Confirm new password",
    "passwordChangeSoon": "Password change endpoint is coming soon.",
    "deleteAccountTitle": "Delete Account",
    "deleteAccountDescription":
        "This action is permanent and will be protected by additional verification.",
    "deleteAccountButton": "Delete account",
    "deleteAccountDialogTitle": "Delete account confirmation",
    "deleteAccountDialogDescription":
        "Enter your account email and password twice to confirm.",
    "confirmEmail": "Confirm email",
    "confirmPasswordAgain": "Confirm password again",
    "deleteAccountEmailMismatch":
        "The entered email does not match the current account.",
    "deleteAccountPasswordMismatch": "Passwords do not match.",
    "deleteAccountFlowSoon": "Delete account flow will be enabled soon.",
    "achievementNoBadges": "No badges unlocked yet",
    "achievementUnlockedNone": "No achievements unlocked",
    "achievementStatusUnlocked": "Unlocked",
    "achievementStatusAvailable": "Can be unlocked",
    "achievementStatusUnavailable": "Unavailable",
    "badgeFounderTitle": "Founder",
    "badgeFounderDescription":
        "CareerSuitUp founding member badge, assigned to founder accounts.",
    "badgeTwoFactorTitle": "2FA Enabled",
    "badgeTwoFactorDescription":
        "You enabled two-factor authentication and improved account security.",
    "educationHighSchool": "High School",
    "educationPostSecondary": "Post-secondary",
    "educationBachelor": "Bachelor",
    "educationMaster": "Master",
    "educationDoctorate": "Doctorate",
  },
};

String _activeLang = 'RO';

void setActiveLanguage(String lang) {
  if (texts.containsKey(lang)) {
    _activeLang = lang;
  }
}

String t(String lang, String key) {
  final fallbackLang = texts.containsKey('EN') ? 'EN' : texts.keys.first;
  final resolvedLang = texts.containsKey(_activeLang)
      ? _activeLang
      : (texts.containsKey(lang) ? lang : fallbackLang);
  final langMap = texts[resolvedLang] ?? texts[fallbackLang]!;
  return langMap[key] ?? texts[fallbackLang]?[key] ?? key;
}

List<String> supportedLanguages() => texts.keys.toList(growable: false);
